version: '3.8'

services:
  # API Gateway service
  gateway:
    image: ninshuti/gateway-service:latest
    container_name: gateway-service
    ports:
      - "4000:4000"  # Exposing port for the API Gateway
    env_file:
      - .env  # This loads all the variables from the .env file into the container

    depends_on:
      - auth-service
      - organization-service

  # Authentication service (Example)
  auth-service:
    image: ninshuti/auth-service:latest
    container_name: auth-service
    ports:
      - "4001:4001"
    env_file:
      - .env  # This loads the environment variables from .env file for auth service
    # Other configuration...

  # Organization service (Example)
  organization-service:
    image: ninshuti/organization-service:latest
    container_name: organization-service
    ports:
      - "4002:4002"
    env_file:
      - .env  # This loads the environment variables from .env file for org service
    # Other configuration...
