services:
  imotrack-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: imotrack-backend:local
    ports:
      - "7017:4000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
